/**
@file		protocol_CRRT_PC_Types.h

@brief		CRRT protocol types definition

@author		Nicola Molinazzi
@date		26/09/2012
@version	01.00
*/

#ifndef _PROTOCOL_CRRT_PC_TYPES_H_
#define _PROTOCOL_CRRT_PC_TYPES_H_
#include "CRRT_types.h"
#include "loader_types.h"

#define PROLOG_DIM      6
#define EPILOG_DIM      2
#define PROTOCOL_DIM    (PROLOG_DIM + EPILOG_DIM)
#define MASTER_ID_POS   0x00
#define SLAVE_ID_POS    0x01
#define PROG_POS        0x02
#define NUM_PAR_POS     0x03
#define CMD_POS         0x05
#define PAR_POS         0x06

#define STX             0x02
#define STX_CODED       0x0202
#define ETX             0x03
#define ETX_CODED       0x0302
#define MAX_PACK_SIZE   2048

#define UNLOCK_TIMEOUT 10000

//------------------------ COMMANDS LIST ---------------------------------

/*********************************************************************/
/***************************** CRRT **********************************/
/*********************************************************************/
//NACK
#define CMD_NACK                        0x01
//ACK
#define CMD_ACK                         0x06
#define CMD_ACK_TX_PAR_MASTER           0
#define CMD_ACK_RX_PAR_MASTER           1
#define CMD_ACK_TX_PAR_SLAVE            CMD_ACK_RX_PAR_MASTER
#define CMD_ACK_RX_PAR_SLAVE            CMD_ACK_TX_PAR_MASTER
//START-STOP
#define CMD_STARTSTOP                   0x28
#define CMD_STARTSTOP_TX_PAR_MASTER     3
#define CMD_STARTSTOP_RX_PAR_MASTER     1
#define CMD_STARTSTOP_TX_PAR_SLAVE      CMD_STARTSTOP_RX_PAR_MASTER
#define CMD_STARTSTOP_RX_PAR_SLAVE      CMD_STARTSTOP_TX_PAR_MASTER
//ABORT
#define CMD_ABORT                       0x29
#define CMD_ABORT_TX_PAR_MASTER         0
#define CMD_ABORT_RX_PAR_MASTER         0
#define CMD_ABORT_TX_PAR_SLAVE          CMD_ABORT_RX_PAR_MASTER
#define CMD_ABORT_RX_PAR_SLAVE          CMD_ABORT_TX_PAR_MASTER
//CALIBRATION
#define CMD_CALIBRATION                   0x2A
#define CMD_CALIBRATION_TX_PAR_MASTER     6
#define CMD_CALIBRATION_RX_PAR_MASTER     (3 + sizeof(gainAndOffset_t))
#define CMD_CALIBRATION_TX_PAR_SLAVE      CMD_CALIBRATION_RX_PAR_MASTER
#define CMD_CALIBRATION_RX_PAR_SLAVE      CMD_CALIBRATION_TX_PAR_MASTER
//CALIBRATION_BLD
#define CMD_CALIBRATION_BLD                   0x52
#define CMD_CALIBRATION_BLD_TX_PAR_MASTER     1
#define CMD_CALIBRATION_BLD_RX_PAR_MASTER     (1+1+2+2+2)
#define CMD_CALIBRATION_BLD_TX_PAR_SLAVE      CMD_CALIBRATION_BLD_RX_PAR_MASTER
#define CMD_CALIBRATION_BLD_RX_PAR_SLAVE      CMD_CALIBRATION_BLD_TX_PAR_MASTER
//SERVICE
#define CMD_SERVICE                      0x2B
#define CMD_SERVICE_TX_PAR_MASTER        1
#define CMD_SERVICE_RX_PAR_MASTER        1
#define CMD_SERVICE_TX_PAR_SLAVE         CMD_SERVICE_RX_PAR_MASTER
#define CMD_SERVICE_RX_PAR_SLAVE         CMD_SERVICE_TX_PAR_MASTER
//PWM_CTRL_SET/GET
#define CMD_PWM_CTRL_GET_SET                  0x2C
#define CMD_PWM_CTRL_GET_SET_TX_PAR_MASTER    7
#define CMD_PWM_CTRL_GET_SET_RX_PAR_MASTER    7
#define CMD_PWM_CTRL_GET_SET_TX_PAR_SLAVE     CMD_PWM_CTRL_GET_SET_RX_PAR_MASTER
#define CMD_PWM_CTRL_GET_SET_RX_PAR_SLAVE     CMD_PWM_CTRL_GET_SET_TX_PAR_MASTER
//GET POWER SUPPLY VOLTAGES
#define CMD_GET_PWR_SUP_VOLT               0x2E
#define CMD_GET_PWR_SUP_VOLT_TX_PAR_MASTER 0
#define CMD_GET_PWR_SUP_VOLT_RX_PAR_MASTER sizeof(servicePowerSupplyStruct_t)
#define CMD_GET_PWR_SUP_VOLT_TX_PAR_SLAVE  CMD_GET_PWR_SUP_VOLT_RX_PAR_MASTER
#define CMD_GET_PWR_SUP_VOLT_RX_PAR_SLAVE  CMD_GET_PWR_SUP_VOLT_TX_PAR_MASTER
//GET/ SET RELAYS
#define CMD_GET_SET_RELAYS               0x2F
#define CMD_GET_SET_RELAYS_TX_PAR_MASTER 3
#define CMD_GET_SET_RELAYS_RX_PAR_MASTER 3
#define CMD_GET_SET_RELAYS_TX_PAR_SLAVE  CMD_GET_SET_RELAYS_RX_PAR_MASTER
#define CMD_GET_SET_RELAYS_RX_PAR_SLAVE  CMD_GET_SET_RELAYS_TX_PAR_MASTER
//GET/ SET SWITCH CLAMP POSITION
#define CMD_GET_SET_SWITCH_CLAMP_POS               0x30
#define CMD_GET_SET_SWITCH_CLAMP_POS_TX_PAR_MASTER 2
#define CMD_GET_SET_SWITCH_CLAMP_POS_RX_PAR_MASTER 2
#define CMD_GET_SET_SWITCH_CLAMP_POS_TX_PAR_SLAVE  CMD_GET_SET_SWITCH_CLAMP_POS_RX_PAR_MASTER
#define CMD_GET_SET_SWITCH_CLAMP_POS_RX_PAR_SLAVE  CMD_GET_SET_SWITCH_CLAMP_POS_TX_PAR_MASTER
//GET/ SET ELECTROCLAMP POSITION
#define CMD_GET_SET_ELECTROCLAMP_POS               0x31
#define CMD_GET_SET_ELECTROCLAMP_POS_TX_PAR_MASTER 2
#define CMD_GET_SET_ELECTROCLAMP_POS_RX_PAR_MASTER 2
#define CMD_GET_SET_ELECTROCLAMP_POS_TX_PAR_SLAVE  CMD_GET_SET_ELECTROCLAMP_POS_RX_PAR_MASTER
#define CMD_GET_SET_ELECTROCLAMP_POS_RX_PAR_SLAVE  CMD_GET_SET_ELECTROCLAMP_POS_TX_PAR_MASTER
//TEST POINT POSITION
#define CMD_TEST_POINT               0x32
#define CMD_TEST_POINT_TX_PAR_MASTER (1 + sizeof(tests_bitF_t))
#define CMD_TEST_POINT_RX_PAR_MASTER (1 + sizeof(tests_bitF_t))
#define CMD_TEST_POINT_TX_PAR_SLAVE  CMD_TEST_POINT_RX_PAR_MASTER
#define CMD_TEST_POINT_RX_PAR_SLAVE  CMD_TEST_POINT_TX_PAR_MASTER
//RESET ALARMS
#define CMD_RESET_ALARMS                       0x33
#define CMD_RESET_ALARMS_TX_PAR_MASTER         0
#define CMD_RESET_ALARMS_RX_PAR_MASTER         1
#define CMD_RESET_ALARMS_TX_PAR_SLAVE          CMD_RESET_ALARMS_RX_PAR_MASTER
#define CMD_RESET_ALARMS_RX_PAR_SLAVE          CMD_RESET_ALARMS_TX_PAR_MASTER
//MUTE ALARMS
#define CMD_MUTE_ALARMS                       0x34
#define CMD_MUTE_ALARMS_TX_PAR_MASTER         0
#define CMD_MUTE_ALARMS_RX_PAR_MASTER         1
#define CMD_MUTE_ALARMS_TX_PAR_SLAVE          CMD_MUTE_ALARMS_RX_PAR_MASTER
#define CMD_MUTE_ALARMS_RX_PAR_SLAVE          CMD_MUTE_ALARMS_TX_PAR_MASTER
//GO STANDBY
#define CMD_GO_STANDBY                       0x35
#define CMD_GO_STANDBY_TX_PAR_MASTER         0
#define CMD_GO_STANDBY_RX_PAR_MASTER         1
#define CMD_GO_STANDBY_TX_PAR_SLAVE          CMD_GO_STANDBY_RX_PAR_MASTER
#define CMD_GO_STANDBY_RX_PAR_SLAVE          CMD_GO_STANDBY_TX_PAR_MASTER
//DROPPER LEVEL
#define CMD_DROPPER_LEVEL                    0x36
#define CMD_DROPPER_LEVEL_TX_PAR_MASTER      1
#define CMD_DROPPER_LEVEL_RX_PAR_MASTER      1
#define CMD_DROPPER_LEVEL_TX_PAR_SLAVE       CMD_DROPPER_LEVEL_RX_PAR_MASTER
#define CMD_DROPPER_LEVEL_RX_PAR_SLAVE       CMD_DROPPER_LEVEL_TX_PAR_MASTER
//GET COMMUNICATION STATISTICS
#define CMD_GET_COMMUNICATION_STATISTICS               0x37
#define CMD_GET_COMMUNICATION_STATISTICS_TX_PAR_MASTER 2
#define CMD_GET_COMMUNICATION_STATISTICS_RX_PAR_MASTER (2 + sizeof(communication_statistics_counters_t))
#define CMD_GET_COMMUNICATION_STATISTICS_TX_PAR_SLAVE  CMD_GET_COMMUNICATION_STATISTICS_RX_PAR_MASTER
#define CMD_GET_COMMUNICATION_STATISTICS_RX_PAR_SLAVE  CMD_GET_COMMUNICATION_STATISTICS_TX_PAR_MASTER
//STEPPER INFO
#define CMD_STEPPER_INFO               0x38
#define CMD_STEPPER_INFO_TX_PAR_MASTER (1 )
#define CMD_STEPPER_INFO_RX_PAR_MASTER (1 + sizeof(stepper_motor_info_t))
#define CMD_STEPPER_INFO_TX_PAR_SLAVE  CMD_STEPPER_INFO_RX_PAR_MASTER
#define CMD_STEPPER_INFO_RX_PAR_SLAVE  CMD_STEPPER_INFO_TX_PAR_MASTER
//GET LOCAL ALARMS
#define CMD_GET_LOCAL_ALARMS                0x39
#define CMD_GET_LOCAL_ALARMS_TX_PAR_MASTER  1
#define CMD_GET_LOCAL_ALARMS_RX_PAR_MASTER  (1 + sizeof(alarms_t))
#define CMD_GET_LOCAL_ALARMS_TX_PAR_SLAVE   CMD_GET_LOCAL_ALARMS_RX_PAR_MASTER
#define CMD_GET_LOCAL_ALARMS_RX_PAR_SLAVE   CMD_GET_LOCAL_ALARMS_TX_PAR_MASTER
// ENABLE LOCAL ALARMS
#define CMD_ENABLE_LOCAL_ALARMS                0x40
#define CMD_ENABLE_LOCAL_ALARMS_TX_PAR_MASTER  sizeof(alarms_t)
#define CMD_ENABLE_LOCAL_ALARMS_RX_PAR_MASTER  (1 + sizeof(alarms_t))
#define CMD_ENABLE_LOCAL_ALARMS_TX_PAR_SLAVE   CMD_ENABLE_LOCAL_ALARMS_RX_PAR_MASTER
#define CMD_ENABLE_LOCAL_ALARMS_RX_PAR_SLAVE   CMD_ENABLE_LOCAL_ALARMS_TX_PAR_MASTER
//STEPPER SAVE ROTOR POSITION
#define CMD_STEPPER_SAVE_ROT_POS               0x41
#define CMD_STEPPER_SAVE_ROT_POS_TX_PAR_MASTER (1)
#define CMD_STEPPER_SAVE_ROT_POS_RX_PAR_MASTER (4)
#define CMD_STEPPER_SAVE_ROT_POS_TX_PAR_SLAVE  CMD_STEPPER_SAVE_ROT_POS_RX_PAR_MASTER
#define CMD_STEPPER_SAVE_ROT_POS_RX_PAR_SLAVE  CMD_STEPPER_SAVE_ROT_POS_TX_PAR_MASTER
//READ_STATUS
#define CMD_READ_STATUS                 0x46
#define CMD_READ_STATUS_TX_PAR_MASTER   0
#define CMD_READ_STATUS_RX_PAR_MASTER   sizeof(CRRT_working_status_t)
#define CMD_READ_STATUS_TX_PAR_SLAVE    CMD_READ_STATUS_RX_PAR_MASTER
#define CMD_READ_STATUS_RX_PAR_SLAVE    CMD_READ_STATUS_TX_PAR_MASTER
//SET PARAMETERS
#define CMD_SET_PARAMS                  0x47
#define CMD_SET_PARAMS_TX_PAR_MASTER    sizeof(treatmentParameters_t)
#define CMD_SET_PARAMS_RX_PAR_MASTER    1
#define CMD_SET_PARAMS_TX_PAR_SLAVE     CMD_SET_PARAMS_RX_PAR_MASTER
#define CMD_SET_PARAMS_RX_PAR_SLAVE     CMD_SET_PARAMS_TX_PAR_MASTER
//GET PARAMETERS
#define CMD_GET_PARAMS                  0x48
#define CMD_GET_PARAMS_TX_PAR_MASTER    0
#define CMD_GET_PARAMS_RX_PAR_MASTER    sizeof(treatmentParameters_t)
#define CMD_GET_PARAMS_TX_PAR_SLAVE     CMD_GET_PARAMS_RX_PAR_MASTER
#define CMD_GET_PARAMS_RX_PAR_SLAVE     CMD_GET_PARAMS_TX_PAR_MASTER
//SET TREATMENT STATUS
#define CMD_SET_TREATMENT_STATUS                  0x49
#define CMD_SET_TREATMENT_STATUS_TX_PAR_MASTER    sizeof(treatmentStatusPara_t)
#define CMD_SET_TREATMENT_STATUS_RX_PAR_MASTER    1
#define CMD_SET_TREATMENT_STATUS_TX_PAR_SLAVE     CMD_SET_TREATMENT_STATUS_RX_PAR_MASTER
#define CMD_SET_TREATMENT_STATUS_RX_PAR_SLAVE     CMD_SET_TREATMENT_STATUS_TX_PAR_MASTER
//GET PRESSURE LIMITS
#define CMD_GET_PRESS_LIM                         0x4A
#define CMD_GET_PRESS_LIM_TX_PAR_MASTER           0
#define CMD_GET_PRESS_LIM_RX_PAR_MASTER           sizeof(pressure_limits_t)
#define CMD_GET_PRESS_LIM_TX_PAR_SLAVE            CMD_GET_PRESS_LIM_RX_PAR_MASTER
#define CMD_GET_PRESS_LIM_RX_PAR_SLAVE            CMD_GET_PRESS_LIM_TX_PAR_MASTER
//SET PRESSURE LIMITS
#define CMD_SET_PRESS_LIM                         0x4B
#define CMD_SET_PRESS_LIM_TX_PAR_MASTER           sizeof(pressure_limits_t)
#define CMD_SET_PRESS_LIM_RX_PAR_MASTER           1
#define CMD_SET_PRESS_LIM_TX_PAR_SLAVE            CMD_SET_PRESS_LIM_RX_PAR_MASTER
#define CMD_SET_PRESS_LIM_RX_PAR_SLAVE            CMD_SET_PRESS_LIM_TX_PAR_MASTER
//BAG CHANGE - SYRINGE CHANGE
#define CMD_BAG_SYRINGE                           0x4C
#define CMD_BAG_SYRINGE_TX_PAR_MASTER             1
#define CMD_BAG_SYRINGE_RX_PAR_MASTER             1
#define CMD_BAG_SYRINGE_TX_PAR_SLAVE              CMD_BAG_SYRINGE_RX_PAR_MASTER
#define CMD_BAG_SYRINGE_RX_PAR_SLAVE              CMD_BAG_SYRINGE_TX_PAR_MASTER
// SYRINGE (HEPARINE) MOVE
#define CMD_SYRINGE_MOVE                          0x4D
#define CMD_SYRINGE_MOVE_TX_PAR_MASTER            1
#define CMD_SYRINGE_MOVE_RX_PAR_MASTER            1
#define CMD_SYRINGE_MOVE_TX_PAR_SLAVE             CMD_SYRINGE_MOVE_RX_PAR_MASTER
#define CMD_SYRINGE_MOVE_RX_PAR_SLAVE             CMD_SYRINGE_MOVE_TX_PAR_MASTER
// BUZZER VOLUME
#define CMD_BUZZER_VOLUME                          0x4E
#define CMD_BUZZER_VOLUME_TX_PAR_MASTER            1
#define CMD_BUZZER_VOLUME_RX_PAR_MASTER            (1 + sizeof(float))
#define CMD_BUZZER_VOLUME_TX_PAR_SLAVE             CMD_BUZZER_VOLUME_RX_PAR_MASTER
#define CMD_BUZZER_VOLUME_RX_PAR_SLAVE             CMD_BUZZER_VOLUME_TX_PAR_MASTER
//READ CURRENT VALUES
#define CMD_GET_CURRENT_VALUES                      0x4F
#define CMD_GET_CURRENT_VALUES_TX_PAR_MASTER        0
#define CMD_GET_CURRENT_VALUES_RX_PAR_MASTER        sizeof(CRRT_current_values_t)
#define CMD_GET_CURRENT_VALUES_TX_PAR_SLAVE         CMD_GET_CURRENT_VALUES_RX_PAR_MASTER
#define CMD_GET_CURRENT_VALUES_RX_PAR_SLAVE         CMD_GET_CURRENT_VALUES_TX_PAR_MASTER
//GET TOTALIZERS
#define CMD_GET_TOTALIZERS                          0x50
#define CMD_GET_TOTALIZERS_TX_PAR_MASTER            0
#define CMD_GET_TOTALIZERS_RX_PAR_MASTER            sizeof(CRRT_totalizers_t)
#define CMD_GET_TOTALIZERS_TX_PAR_SLAVE             CMD_GET_TOTALIZERS_RX_PAR_MASTER
#define CMD_GET_TOTALIZERS_RX_PAR_SLAVE             CMD_GET_TOTALIZERS_TX_PAR_MASTER
//GET ALARMS
#define CMD_GET_ALARMS                              0x51
#define CMD_GET_GET_ALARMS_TX_PAR_MASTER            0
#define CMD_GET_GET_ALARMS_RX_PAR_MASTER            sizeof(alarms_t)
#define CMD_GET_GET_ALARMS_TX_PAR_SLAVE             CMD_GET_GET_ALARMS_RX_PAR_MASTER
#define CMD_GET_GET_ALARMS_RX_PAR_SLAVE             CMD_GET_GET_ALARMS_TX_PAR_MASTER
//SET LIGHT
#define CMD_SET_LIGHT                               0x53
#define CMD_SET_LIGHT_TX_PAR_MASTER                 2
#define CMD_SET_LIGHT_RX_PAR_MASTER                 1
#define CMD_SET_LIGHT_TX_PAR_SLAVE                  CMD_SET_LIGHT_RX_PAR_MASTER
#define CMD_SET_LIGHT_RX_PAR_SLAVE                  CMD_SET_LIGHT_TX_PAR_MASTER
//SET HEATER
#define CMD_SET_HEATER                              0x54
#define CMD_SET_HEATER_TX_PAR_MASTER                (1+1+sizeof(uint16_t))
#define CMD_SET_HEATER_RX_PAR_MASTER                (1+1+sizeof(uint16_t) + 1)
#define CMD_SET_HEATER_TX_PAR_SLAVE                 CMD_SET_HEATER_RX_PAR_MASTER
#define CMD_SET_HEATER_RX_PAR_SLAVE                 CMD_SET_HEATER_TX_PAR_MASTER
//SET BUZZER
#define CMD_SET_BUZZER                              0x55
#define CMD_SET_BUZZER_TX_PAR_MASTER                (1)
#define CMD_SET_BUZZER_RX_PAR_MASTER                (1)
#define CMD_SET_BUZZER_TX_PAR_SLAVE                 CMD_SET_BUZZER_RX_PAR_MASTER
#define CMD_SET_BUZZER_RX_PAR_SLAVE                 CMD_SET_BUZZER_TX_PAR_MASTER
//READ VERSION
#define CMD_READ_VERSION                 0xD2
#define CMD_READ_VERSION_TX_PAR_MASTER   0
#define CMD_READ_VERSION_RX_PAR_MASTER   (46+50)
#define CMD_READ_VERSION_TX_PAR_SLAVE    CMD_READ_VERSION_RX_PAR_MASTER
#define CMD_READ_VERSION_RX_PAR_SLAVE    CMD_READ_VERSION_TX_PAR_MASTER
//MOTORS
#define CMD_MOTOR                       0xD3
#define CMD_MOTOR_TX_PAR_MASTER         (sizeof(motor_t) +1)
#define CMD_MOTOR_RX_PAR_MASTER         1
#define CMD_MOTOR_TX_PAR_SLAVE          CMD_MOTOR_RX_PAR_MASTER
#define CMD_MOTOR_RX_PAR_SLAVE          CMD_MOTOR_TX_PAR_MASTER

/*********************************************************************/
/***************************** SPS ***********************************/
/*********************************************************************/
//ACK_SPS
#define CMD_SPS_ACK                         0x064
#define CMD_SPS_ACK_TX_PAR_MASTER           0
#define CMD_SPS_ACK_RX_PAR_MASTER           1
#define CMD_SPS_ACK_TX_PAR_SLAVE            CMD_SPS_ACK_RX_PAR_MASTER
#define CMD_SPS_ACK_RX_PAR_SLAVE            CMD_SPS_ACK_TX_PAR_MASTER
//MOTORS_SPS
#define CMD_SPS_MOTOR                       0x65
#define CMD_SPS_MOTOR_TX_PAR_MASTER         (sizeof(motor_t) +1)
#define CMD_SPS_MOTOR_RX_PAR_MASTER         1
#define CMD_SPS_MOTOR_TX_PAR_SLAVE          CMD_SPS_MOTOR_RX_PAR_MASTER
#define CMD_SPS_MOTOR_RX_PAR_SLAVE          CMD_SPS_MOTOR_TX_PAR_MASTER
//READ_STATUS_SPS
#define CMD_SPS_READ_STATUS                 0x60
#define CMD_SPS_READ_STATUS_TX_PAR_MASTER   0
#define CMD_SPS_READ_STATUS_RX_PAR_MASTER   sizeof(SPS_status_t)
#define CMD_SPS_READ_STATUS_TX_PAR_SLAVE    CMD_SPS_READ_STATUS_RX_PAR_MASTER
#define CMD_SPS_READ_STATUS_RX_PAR_SLAVE    CMD_SPS_READ_STATUS_TX_PAR_MASTER
//SPS_SELECTOR BAG TO FILL
#define CMD_SPS_SELECTOR_BAG_TO_FILL                    0x61
#define CMD_SPS_SELECTOR_BAG_TO_FILL_TX_PAR_MASTER      1       //valore
#define CMD_SPS_SELECTOR_BAG_TO_FILL_RX_PAR_MASTER      1
#define CMD_SPS_SELECTOR_BAG_TO_FILL_TX_PAR_SLAVE       CMD_SPS_SELECTOR_BAG_TO_FILL_RX_PAR_MASTER
#define CMD_SPS_SELECTOR_BAG_TO_FILL_RX_PAR_SLAVE       CMD_SPS_SELECTOR_BAG_TO_FILL_TX_PAR_MASTER
//SPS_SELECTOR BAG TO EMPTY
#define CMD_SPS_SELECTOR_BAG_TO_EMPTY                   0x81
#define CMD_SPS_SELECTOR_BAG_TO_EMPTY_TX_PAR_MASTER      1       //valore
#define CMD_SPS_SELECTOR_BAG_TO_EMPTY_RX_PAR_MASTER      1
#define CMD_SPS_SELECTOR_BAG_TO_EMPTY_TX_PAR_SLAVE       CMD_SPS_SELECTOR_BAG_TO_EMPTY_RX_PAR_MASTER
#define CMD_SPS_SELECTOR_BAG_TO_EMPTY_RX_PAR_SLAVE       CMD_SPS_SELECTOR_BAG_TO_EMPTY_TX_PAR_MASTER
//SPS_VALVE
#define CMD_SPS_VALVE                       0x62
#define CMD_SPS_VALVE_TX_PAR_MASTER         2       // n° valvola e stato
#define CMD_SPS_VALVE_RX_PAR_MASTER         1
#define CMD_SPS_VALVE_TX_PAR_SLAVE          CMD_SPS_VALVE_RX_PAR_MASTER
#define CMD_SPS_VALVE_RX_PAR_SLAVE          CMD_SPS_VALVE_TX_PAR_MASTER
//SPS_CALIBRATION
#define CMD_SPS_CALIBRATION                 0x63
#define CMD_SPS_CALIBRATION_TX_PAR_MASTER   6
#define CMD_SPS_CALIBRATION_RX_PAR_MASTER   (3+sizeof(sps_gainAndOffset_t))
#define CMD_SPS_CALIBRATION_TX_PAR_SLAVE    CMD_SPS_CALIBRATION_RX_PAR_MASTER
#define CMD_SPS_CALIBRATION_RX_PAR_SLAVE    CMD_SPS_CALIBRATION_TX_PAR_MASTER
//START-STOP_SPS
#define CMD_SPS_STARTSTOP                   0x66
#define CMD_SPS_STARTSTOP_TX_PAR_MASTER     3
#define CMD_SPS_STARTSTOP_RX_PAR_MASTER     1
#define CMD_SPS_STARTSTOP_TX_PAR_SLAVE      CMD_SPS_STARTSTOP_RX_PAR_MASTER
#define CMD_SPS_STARTSTOP_RX_PAR_SLAVE      CMD_SPS_STARTSTOP_TX_PAR_MASTER
//ABORT_SPS
#define CMD_SPS_ABORT                       0x67
#define CMD_SPS_ABORT_TX_PAR_MASTER         0
#define CMD_SPS_ABORT_RX_PAR_MASTER         0
#define CMD_SPS_ABORT_TX_PAR_SLAVE          CMD_SPS_ABORT_RX_PAR_MASTER
#define CMD_SPS_ABORT_RX_PAR_SLAVE          CMD_SPS_ABORT_TX_PAR_MASTER
//RESET ALARMS_SPS
#define CMD_SPS_RESET_ALARMS                       0x68
#define CMD_SPS_RESET_ALARMS_TX_PAR_MASTER         0
#define CMD_SPS_RESET_ALARMS_RX_PAR_MASTER         1
#define CMD_SPS_RESET_ALARMS_TX_PAR_SLAVE          CMD_SPS_RESET_ALARMS_RX_PAR_MASTER
#define CMD_SPS_RESET_ALARMS_RX_PAR_SLAVE          CMD_SPS_RESET_ALARMS_TX_PAR_MASTER
//MUTE ALARMS_SPS
#define CMD_SPS_MUTE_ALARMS                       0x69
#define CMD_SPS_MUTE_ALARMS_TX_PAR_MASTER         0
#define CMD_SPS_MUTE_ALARMS_RX_PAR_MASTER         1
#define CMD_SPS_MUTE_ALARMS_TX_PAR_SLAVE          CMD_SPS_MUTE_ALARMS_RX_PAR_MASTER
#define CMD_SPS_MUTE_ALARMS_RX_PAR_SLAVE          CMD_SPS_MUTE_ALARMS_TX_PAR_MASTER
//READ VERSION_SPS
#define CMD_SPS_READ_VERSION                 0x70
#define CMD_SPS_READ_VERSION_TX_PAR_MASTER   0
#define CMD_SPS_READ_VERSION_RX_PAR_MASTER   (46+75) //info cpu + info ADuC
#define CMD_SPS_READ_VERSION_TX_PAR_SLAVE    CMD_SPS_READ_VERSION_RX_PAR_MASTER
#define CMD_SPS_READ_VERSION_RX_PAR_SLAVE    CMD_SPS_READ_VERSION_TX_PAR_MASTER
//SERVICE_SPS
#define CMD_SPS_SERVICE                      0x71
#define CMD_SPS_SERVICE_TX_PAR_MASTER        1
#define CMD_SPS_SERVICE_RX_PAR_MASTER        1
#define CMD_SPS_SERVICE_TX_PAR_SLAVE         CMD_SPS_SERVICE_RX_PAR_MASTER
#define CMD_SPS_SERVICE_RX_PAR_SLAVE         CMD_SPS_SERVICE_TX_PAR_MASTER
//GET POWER SUPPLY VOLTAGES_SPS
#define CMD_SPS_GET_PWR_SUP_VOLT               0x72
#define CMD_SPS_GET_PWR_SUP_VOLT_TX_PAR_MASTER 0
#define CMD_SPS_GET_PWR_SUP_VOLT_RX_PAR_MASTER sizeof(sps_servicePowerSupplyStruct_t)
#define CMD_SPS_GET_PWR_SUP_VOLT_TX_PAR_SLAVE  CMD_SPS_GET_PWR_SUP_VOLT_RX_PAR_MASTER
#define CMD_SPS_GET_PWR_SUP_VOLT_RX_PAR_SLAVE  CMD_SPS_GET_PWR_SUP_VOLT_TX_PAR_MASTER
//GET/ SET RELAYS_SPS
#define CMD_SPS_GET_SET_RELAYS               0x73
#define CMD_SPS_GET_SET_RELAYS_TX_PAR_MASTER 3
#define CMD_SPS_GET_SET_RELAYS_RX_PAR_MASTER 3
#define CMD_SPS_GET_SET_RELAYS_TX_PAR_SLAVE  CMD_SPS_GET_SET_RELAYS_RX_PAR_MASTER
#define CMD_SPS_GET_SET_RELAYS_RX_PAR_SLAVE  CMD_SPS_GET_SET_RELAYS_TX_PAR_MASTER
//TEST POINT POSITION_SPS
#define CMD_SPS_TEST_POINT               0x74
#define CMD_SPS_TEST_POINT_TX_PAR_MASTER (1 + sizeof(sps_tests_bitF_t))
#define CMD_SPS_TEST_POINT_RX_PAR_MASTER (1 + sizeof(sps_tests_bitF_t))
#define CMD_SPS_TEST_POINT_TX_PAR_SLAVE  CMD_SPS_TEST_POINT_RX_PAR_MASTER
#define CMD_SPS_TEST_POINT_RX_PAR_SLAVE  CMD_SPS_TEST_POINT_TX_PAR_MASTER
//GET COMMUNICATION STATISTICS_SPS
#define CMD_SPS_GET_COMMUNICATION_STATISTICS               0x75
#define CMD_SPS_GET_COMMUNICATION_STATISTICS_TX_PAR_MASTER 2
#define CMD_SPS_GET_COMMUNICATION_STATISTICS_RX_PAR_MASTER (2 + sizeof(communication_statistics_counters_t))
#define CMD_SPS_GET_COMMUNICATION_STATISTICS_TX_PAR_SLAVE  CMD_SPS_GET_COMMUNICATION_STATISTICS_RX_PAR_MASTER
#define CMD_SPS_GET_COMMUNICATION_STATISTICS_RX_PAR_SLAVE  CMD_SPS_GET_COMMUNICATION_STATISTICS_TX_PAR_MASTER
//STEPPER INFO
#define CMD_SPS_STEPPER_INFO               0x76
#define CMD_SPS_STEPPER_INFO_TX_PAR_MASTER (1 )
#define CMD_SPS_STEPPER_INFO_RX_PAR_MASTER (1 + sizeof(stepper_motor_info_t))
#define CMD_SPS_STEPPER_INFO_TX_PAR_SLAVE  CMD_SPS_STEPPER_INFO_RX_PAR_MASTER
#define CMD_SPS_STEPPER_INFO_RX_PAR_SLAVE  CMD_SPS_STEPPER_INFO_TX_PAR_MASTER
// GET LOCAL ALARMS_SPS
#define CMD_SPS_GET_LOCAL_ALARMS                0x78
#define CMD_SPS_GET_LOCAL_ALARMS_TX_PAR_MASTER  1
#define CMD_SPS_GET_LOCAL_ALARMS_RX_PAR_MASTER  (1 + sizeof(sps_alarms_t))
#define CMD_SPS_GET_LOCAL_ALARMS_TX_PAR_SLAVE   CMD_SPS_GET_LOCAL_ALARMS_RX_PAR_MASTER
#define CMD_SPS_GET_LOCAL_ALARMS_RX_PAR_SLAVE   CMD_SPS_GET_LOCAL_ALARMS_TX_PAR_MASTER
// ENABLE LOCAL ALARMS
#define CMD_SPS_ENABLE_LOCAL_ALARMS                0x79
#define CMD_SPS_ENABLE_LOCAL_ALARMS_TX_PAR_MASTER  sizeof(sps_alarms_t)
#define CMD_SPS_ENABLE_LOCAL_ALARMS_RX_PAR_MASTER  (1 + sizeof(sps_alarms_t))
#define CMD_SPS_ENABLE_LOCAL_ALARMS_TX_PAR_SLAVE   CMD_SPS_ENABLE_LOCAL_ALARMS_RX_PAR_MASTER
#define CMD_SPS_ENABLE_LOCAL_ALARMS_RX_PAR_SLAVE   CMD_SPS_ENABLE_LOCAL_ALARMS_TX_PAR_MASTER
//STEPPER SAVE ROTOR POSITION
#define CMD_SPS_STEPPER_SAVE_ROT_POS               0x80
#define CMD_SPS_STEPPER_SAVE_ROT_POS_TX_PAR_MASTER (1)
#define CMD_SPS_STEPPER_SAVE_ROT_POS_RX_PAR_MASTER (4)
#define CMD_SPS_STEPPER_SAVE_ROT_POS_TX_PAR_SLAVE  CMD_SPS_STEPPER_SAVE_ROT_POS_RX_PAR_MASTER
#define CMD_SPS_STEPPER_SAVE_ROT_POS_RX_PAR_SLAVE  CMD_SPS_STEPPER_SAVE_ROT_POS_TX_PAR_MASTER

/*********************************************************************/
/***************************** LOADER ********************************/
/*********************************************************************/
// STATUS REQUEST
#define CMD_LOADER_READ_STATUS						0x90
#define CMD_LOADER_READ_STATUS_TX_PAR_MASTER		0
#define CMD_LOADER_READ_STATUS_RX_PAR_MASTER		sizeof(loaderStatus_t)
#define CMD_LOADER_READ_STATUS_TX_PAR_SLAVE			CMD_LOADER_READ_STATUS_RX_PAR_MASTER
#define CMD_LOADER_READ_STATUS_RX_PAR_SLAVE			CMD_LOADER_READ_STATUS_TX_PAR_MASTER
// LOADER INFO
#define CMD_LOADER_INFO     						0x91
#define CMD_LOADER_INFO_TX_PAR_MASTER               0
#define CMD_LOADER_INFO_RX_PAR_MASTER               sizeof(application_info_data_t)
#define CMD_LOADER_INFO_TX_PAR_SLAVE                CMD_LOADER_INFO_RX_PAR_MASTER
#define CMD_LOADER_INFO_RX_PAR_SLAVE                CMD_LOADER_INFO_TX_PAR_MASTER
// LOADED APP INFO
#define CMD_LOADED_APP_INFO         				0x92
#define CMD_LOADED_APP_INFO_TX_PAR_MASTER           0
#define CMD_LOADED_APP_INFO_RX_PAR_MASTER           sizeof(application_info_data_t)
#define CMD_LOADED_APP_INFO_TX_PAR_SLAVE			CMD_LOADED_APP_INFO_RX_PAR_MASTER
#define CMD_LOADED_APP_INFO_RX_PAR_SLAVE			CMD_LOADED_APP_INFO_TX_PAR_MASTER
// FLASH INIT
#define CMD_LOADER_FLASH_INIT       				0x93
#define CMD_LOADER_FLASH_INIT_TX_PAR_MASTER         12
#define CMD_LOADER_FLASH_INIT_RX_PAR_MASTER         1
#define CMD_LOADER_FLASH_INIT_TX_PAR_SLAVE			CMD_LOADER_FLASH_INIT_RX_PAR_MASTER
#define CMD_LOADER_FLASH_INIT_RX_PAR_SLAVE			CMD_LOADER_FLASH_INIT_TX_PAR_MASTER
// FLASH UNINIT
#define CMD_LOADER_FLASH_UNINIT       				0x94
#define CMD_LOADER_FLASH_UNINIT_TX_PAR_MASTER       4
#define CMD_LOADER_FLASH_UNINIT_RX_PAR_MASTER       1
#define CMD_LOADER_FLASH_UNINIT_TX_PAR_SLAVE		CMD_LOADER_FLASH_UNINIT_RX_PAR_MASTER
#define CMD_LOADER_FLASH_UNINIT_RX_PAR_SLAVE        CMD_LOADER_FLASH_UNINIT_TX_PAR_MASTER
// BLANK CHECK
#define CMD_LOADER_BLANK_CHECK						0x95
#define CMD_LOADER_BLANK_CHECK_TX_PAR_MASTER		8
#define CMD_LOADER_BLANK_CHECK_RX_PAR_MASTER		1
#define CMD_LOADER_BLANK_CHECK_TX_PAR_SLAVE			CMD_LOADER_BLANK_CHECK_RX_PAR_MASTER
#define CMD_LOADER_BLANK_CHECK_RX_PAR_SLAVE			CMD_LOADER_BLANK_CHECK_TX_PAR_MASTER
// CHIP ERASE
#define CMD_LOADER_CHIP_ERASE						0x96
#define CMD_LOADER_CHIP_ERASE_TX_PAR_MASTER			0
#define CMD_LOADER_CHIP_ERASE_RX_PAR_MASTER			1
#define CMD_LOADER_CHIP_ERASE_TX_PAR_SLAVE			CMD_LOADER_CHIP_ERASE_RX_PAR_MASTER
#define CMD_LOADER_CHIP_ERASE_RX_PAR_SLAVE			CMD_LOADER_CHIP_ERASE_TX_PAR_MASTER
// WRITE BLOCK
#define CMD_LOADER_WRITE_BLOCK						0x97
#define CMD_LOADER_WRITE_BLOCK_TX_PAR_MASTER		(4+4+1024)
#define CMD_LOADER_WRITE_BLOCK_RX_PAR_MASTER		1
#define CMD_LOADER_WRITE_BLOCK_TX_PAR_SLAVE			CMD_LOADER_WRITE_BLOCK_RX_PAR_MASTER
#define CMD_LOADER_WRITE_BLOCK_RX_PAR_SLAVE			CMD_LOADER_WRITE_BLOCK_TX_PAR_MASTER
// READ BLOCK
#define CMD_LOADER_READ_BLOCK						0x98
#define CMD_LOADER_READ_BLOCK_TX_PAR_MASTER			(4+4+1024)
#define CMD_LOADER_READ_BLOCK_RX_PAR_MASTER			1
#define CMD_LOADER_READ_BLOCK_TX_PAR_SLAVE			CMD_LOADER_READ_BLOCK_RX_PAR_MASTER
#define CMD_LOADER_READ_BLOCK_RX_PAR_SLAVE			CMD_LOADER_READ_BLOCK_TX_PAR_MASTER
// VERIFY BLOCK
#define CMD_LOADER_VERIFY_BLOCK						0x99
#define CMD_LOADER_VERIFY_BLOCK_TX_PAR_MASTER		(4+4+1024)
#define CMD_LOADER_VERIFY_BLOCK_RX_PAR_MASTER		1
#define CMD_LOADER_VERIFY_BLOCK_TX_PAR_SLAVE		CMD_LOADER_VERIFY_BLOCK_RX_PAR_MASTER
#define CMD_LOADER_VERIFY_BLOCK_RX_PAR_SLAVE		CMD_LOADER_VERIFY_BLOCK_TX_PAR_MASTER
// BLOCK ERASE
#define CMD_LOADER_BLOCK_ERASE						0x9A
#define CMD_LOADER_BLOCK_ERASE_TX_PAR_MASTER		4
#define CMD_LOADER_BLOCK_ERASE_RX_PAR_MASTER		1
#define CMD_LOADER_BLOCK_ERASE_TX_PAR_SLAVE			CMD_LOADER_BLOCK_ERASE_RX_PAR_MASTER
#define CMD_LOADER_BLOCK_ERASE_RX_PAR_SLAVE			CMD_LOADER_BLOCK_ERASE_TX_PAR_MASTER
// RE-WRITE LOADER
#define CMD_LOADER_REWR_LOADER						0x9B
#define CMD_LOADER_REWR_LOADER_TX_PAR_MASTER		4
#define CMD_LOADER_REWR_LOADER_RX_PAR_MASTER		1
#define CMD_LOADER_REWR_LOADER_TX_PAR_SLAVE			CMD_LOADER_REWR_LOADER_RX_PAR_MASTER
#define CMD_LOADER_REWR_LOADER_RX_PAR_SLAVE			CMD_LOADER_REWR_LOADER_TX_PAR_MASTER
// JUMP TO APPLICATION FIRMWARE
#define CMD_LOADER_JUMP_TO_APP						0x9C
#define CMD_LOADER_JUMP_TO_APP_TX_PAR_MASTER		4
#define CMD_LOADER_JUMP_TO_APP_RX_PAR_MASTER		1
#define CMD_LOADER_JUMP_TO_APP_TX_PAR_SLAVE			CMD_LOADER_JUMP_TO_APP_RX_PAR_MASTER
#define CMD_LOADER_JUMP_TO_APP_RX_PAR_SLAVE			CMD_LOADER_JUMP_TO_APP_TX_PAR_MASTER
// JUMP TO LOADER
#define CMD_LOADER_JUMP_TO_LOADER					0x9D
#define CMD_LOADER_JUMP_TO_LOADER_TX_PAR_MASTER		4
#define CMD_LOADER_JUMP_TO_LOADER_RX_PAR_MASTER		1
#define CMD_LOADER_JUMP_TO_LOADER_TX_PAR_SLAVE		CMD_LOADER_JUMP_TO_LOADER_RX_PAR_MASTER
#define CMD_LOADER_JUMP_TO_LOADER_RX_PAR_SLAVE		CMD_LOADER_JUMP_TO_LOADER_TX_PAR_MASTER

//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------

//SCALES CALIBRATION POINTS
#define SCALE_PHY_FIRST_CAL_POINT       0
#define SCALE_PHY_SECOND_CAL_POINT      5000
//PRS CALIBRATION POINTS
#define PRS_PHY_FIRST_CAL_POINT         0
#define PRS_PHY_SECOND_CAL_POINT        200
// CONDUCTIVITY CALIBRATIONS POINTS
#define COND_PHY_FIRST_CAL_POINT        8974
#define COND_PHY_SECOND_CAL_POINT       12880
// TEMP-OHM CALIBRATIONS POINTS
#define TEMP_OHM_PHY_FIRST_CAL_POINT    0
#define TEMP_OHM_PHY_SECOND_CAL_POINT       1207

enum getOrSetCmd_t
{
    ECMD_GET = 0,
    ECMD_SET
}__attribute__ ((packed));
#ifdef __cplusplus
#else
typedef struct getSetCmd_t 	getSetCmd_t;
#endif

/**
 * communication protocols present
 */
enum communication_protocols_present_t
{
    ECOMM_PROTOCOL_PC = 0,
    ECOMM_PROTOCOL_CPU,
    ECOMM_PROTOCOL_SCALES,
    ECOMM_PROTOCOL_PRS,
    ECOMM_PROTOCOL_NUM
}__attribute__ ((packed));
#ifdef __cplusplus
#else
typedef enum communication_protocols_present_t 	communication_protocols_present_t;
#endif

/**
 * communication protocols present
 */
enum sps_communication_protocols_present_t
{
    ESCOMM_PROTOCOL_CRRT = 0,
    ESCOMM_PROTOCOL_CPU,
    ESCOMM_PROTOCOL_SCALES,
    ESCOMM_PROTOCOL_COND_A,
    ESCOMM_PROTOCOL_COND_AB,
    ESCOMM_PROTOCOL_NUM
}__attribute__ ((packed));
#ifdef __cplusplus
#else
typedef enum sps_communication_protocols_present_t 	sps_communication_protocols_present_t;
#endif

/**
  * Communication error types
  */
enum communication_statistics_types_t
{
    ECOMM_TOTAL_TX =0,
    ECOMM_TOTAL_RX,
    ECOMM_TOTAL_ERRORS,
    ECOMM_ERRT_HW_RECEPTION ,
    ECOMM_ERRT_HW_PARITY,
    ECOMM_ERRT_HW_FRAME,
    ECOMM_ERRT_HW_OVERRUN,
    ECOMM_ERRT_HW_NO_DEVICE,
    ECOMM_ERRT_HW_OVERFLOW_RX_BUFFER,
    ECOMM_ERRT_HW_UNKNOWN,

    ECOMM_ERRT_UNKNOWN_OPCODE,
    ECOMM_ERRT_STX_NOT_RECEIVED,
    ECOMM_ERRT_ETX_NOT_RECEIVED,
    ECOMM_ERRT_MODULE_RESPONSE_ERROR,
    ECOMM_ERRT_TIMEOUT_RX,
    ECOMM_ERRT_TIMEOUT_TX,
    ECOMM_ERRT_CHECKSUM,
    ECOMM_ERRT_TRANSMIT_BUFFER_OVERFLOW,
    ECOMM_ERRT_RECEPTION_BUFFER_OVERFLOW,
    ECOMM_ERRT_DATA_RECEIVED_BUFFER_OVERFLOW,
    ECOMM_ERRT_ENCODING,

    ECOMM_ERRT_RX_FIFO_OVERRUN,
    ECOMM_ERRT_TX_FIFO_OVERRUN,

    ECOMM_ERRT_UNKNOWN,

    ECOMM_ERRT_TIMEOUT_ON_STATUS,
    ECOMM_ERRT_OTHER_1,
    ECOMM_ERRT_OTHER_2,
    ECOMM_ERRT_OTHER_3,
    ECOMM_ERRT_OTHER_4,

    ECOMM_STATISTICS_NUM
}__attribute__ ((packed));
#ifdef __cplusplus
#else
typedef enum communication_statistics_types_t 	communication_statistics_types_t;
#endif

/**
 * communication error counters
 */
struct communication_statistics_counters_t
{
    uint16_t counter[ECOMM_STATISTICS_NUM];

#ifdef __cplusplus
    communication_statistics_counters_t()
    {
        for( uint16_t i = 0; i < sizeof(communication_statistics_counters_t); i++)
            *((uint8_t*)(((uint8_t*)this)+i)) = 0;
    }

    communication_statistics_counters_t(const communication_statistics_counters_t &__val)
    {
        for( uint16_t i = 0; i < sizeof(communication_statistics_counters_t); i++)
            *((uint8_t*)(((uint8_t*)this)+i)) = *((uint8_t*)(((uint8_t*)&__val)+i));
    }

    communication_statistics_counters_t& operator= (const communication_statistics_counters_t &__val)
    {
        for( uint16_t i = 0; i < sizeof(communication_statistics_counters_t); i++)
            *((uint8_t*)(((uint8_t*)this)+i)) = *((uint8_t*)(((uint8_t*)&__val)+i));
        return *this;
    }

    void reset()
    {
        for( uint16_t i = 0; i < sizeof(communication_statistics_counters_t); i++)
            *((uint8_t*)(((uint8_t*)this)+i)) = 0;
    }
#endif
}__attribute ((packed));
#ifdef __cplusplus
#else
typedef struct communication_statistics_counters_t 	communication_statistics_counters_t;
#endif

#endif // CRRT_PROTOCOLTYPES_H
